version: "3.3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: rkobylinski/soap:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.3"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - 8080:8080
    networks:
      - default
networks:
  default:
    driver: overlay
    attachable: true